# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "sam-boilerplate-stg"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-onemjhcyapmr"
#s3_resolve = true
s3_prefix = "sam-boilerplate-stg"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Stage=\"staging\""
image_repositories = []
confirm_changeset = true

[product]
[product.deploy]
[product.deploy.parameters]
stack_name = "sam-boilerplate-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-onemjhcyapmr"
#s3_resolve = true
s3_prefix = "sam-boilerplate-prod"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Stage=\"product\""
image_repositories = []
confirm_changeset = true