AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-boilerplate

  Sample SAM Template for sam-boilerplate

Parameters:
  Stage:
    Type: String
    Default: staging
    AllowedValues:
      - staging
      - product

Mappings:
  Configs:
    staging:
      S3Bucket: sam-boilerplate-stg-s3
    product:
      S3Bucket: sam-boilerplate-prod-s3

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:
  S3Stack:
    Type: AWS::Serverless::Application
    Properties:
      Location: infrastructure/s3.yaml
      Parameters:
        S3Bucket: !FindInMap [ Configs, !Ref Stage, S3Bucket ]

  RoleStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: infrastructure/role.yaml
      Parameters:
        S3Bucket: !FindInMap [ Configs, !Ref Stage, S3Bucket ]

  ApiStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: infrastructure/api.yaml
      Parameters:
        Stage: !Ref Stage
        S3Bucket: !FindInMap [ Configs, !Ref Stage, S3Bucket ]
        RoleArn: !GetAtt RoleStack.Outputs.RootAccessRoleArn

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'